[default.extend-words]
FO = "FO"
fo = "fo"
SART = "SART"
Ser = "Ser"
BA = "BA"
ba = "ba"

[files]
extend-exclude = [
    "msvc/",
    "Source/Web/WebDB.cpp",
    "Source/JSON/JSONAIS.cpp",
    "frontend/",
    "CMakeLists.txt",
    "Source/Tracking/RegionTree.cpp",
    "data/regions/",
]
