#!/usr/bin/env python3
"""
Build the marine-region lookup from data/regions/ (run from the repo root):

    python3 scripts/regions/build_regions.py [--csv regions.csv]

Writes Source/Tracking/RegionTree.cpp (the lookup table) and
frontend/src/core/regionNames.js (id -> name for the viewer). Needs shapely.
How the table is built, and how to add a region, is in data/regions/README.md.
"""
import argparse, collections, glob, json, os, sys, time

from shapely import make_valid
from shapely.geometry import shape, box
from shapely.ops import unary_union
from shapely.prepared import prep

SEA_EDGE_DEG = 0.5          # edge between two seas: an arbitrary open-water line
INLAND_EDGE_DEG = 1 / 32    # edge involving a lake or waterway: it meets a sea with a lower id
SEA_SHORE_DEG = 0.5         # shoreline of a sea: coarse, inland still reads as no region
INLAND_SHORE_DEG = 1 / 16   # shoreline of a lake: smaller, so overshoot onto land matters more
MIN_COVER = 0.1             # a region claims a cell it does not contain only when it covers this much of it
MAX_ID = 4096               # ids index the name table; contributed regions start at 2000
NONE = 0xFFFF
INLAND = ("Lake", "Reservoir", "Alkaline Lake", "River", "Canal")

Region = collections.namedtuple("Region", "id name featurecla geom prep edge shore")


def load(src):
    regions = {}
    files = sorted(glob.glob(os.path.join(src, "**", "*.geojson"), recursive=True))
    for path in files:
        j = json.load(open(path, encoding="utf-8"))
        for f in (j["features"] if j.get("type") == "FeatureCollection" else [j]):
            p = f["properties"]
            rid = int(p["id"])
            if rid in regions or not 0 <= rid < MAX_ID:
                sys.exit("%s: bad or duplicate id %d (%s)" % (path, rid, p.get("name")))
            geom = shape(f["geometry"])
            if not geom.is_valid:
                # hand-drawn polygons are often slightly off
                parts = [g for g in getattr(make_valid(geom), "geoms", [make_valid(geom)]) if g.geom_type in ("Polygon", "MultiPolygon")]
                if not parts:
                    sys.exit("%s: geometry cannot be repaired" % path)
                geom = unary_union(parts)
                print("warning: %s: geometry repaired" % os.path.relpath(path, src))
            inland = p.get("featurecla") in INLAND
            regions[rid] = Region(rid, p.get("name", ""), p.get("featurecla", ""), geom, prep(geom),
                                  float(p.get("min_cell", INLAND_EDGE_DEG if inland else SEA_EDGE_DEG)),
                                  INLAND_SHORE_DEG if inland else SEA_SHORE_DEG)
    if not regions:
        sys.exit("no regions under " + src)
    return regions


def build(regions):
    """Quadtree leaves as (level, cx, cy, id); the rule is described in data/regions/README.md."""
    leaves = []

    def visit(level, cx, cy, minx, miny, maxx, maxy, candidates):
        cell = box(minx, miny, maxx, maxy)
        hit = [r for r in candidates if r.prep.intersects(cell)]
        inside = [r for r in hit if r.prep.contains(cell)]
        floor = (hit[0].shore if len(hit) == 1 else min(r.edge for r in hit)) if hit else 0
        if not hit or len(inside) == len(hit) or (maxx - minx) <= floor or (maxy - miny) <= floor:
            ok = [r.id for r in hit if r in inside or r.geom.intersection(cell).area >= MIN_COVER * cell.area]
            leaves.append((level, cx, cy, max(ok) if ok else NONE))
            return
        mx, my = (minx + maxx) / 2, (miny + maxy) / 2
        visit(level + 1, 2 * cx,     2 * cy,     minx, miny, mx,   my,   hit)
        visit(level + 1, 2 * cx + 1, 2 * cy,     mx,   miny, maxx, my,   hit)
        visit(level + 1, 2 * cx,     2 * cy + 1, minx, my,   mx,   maxy, hit)
        visit(level + 1, 2 * cx + 1, 2 * cy + 1, mx,   my,   maxx, maxy, hit)

    visit(0, 0, 0, -180.0, -90.0, 180.0, 90.0, [regions[k] for k in sorted(regions)])
    return leaves


def spread(v, bits):
    return sum(((v >> i) & 1) << (2 * i) for i in range(bits))


def runs_of(leaves):
    """Leaves sorted by Morton key, runs of equal ids merged."""
    levels = max(l for l, _, _, _ in leaves)
    keyed = sorted(((spread(cx, l) | spread(cy, l) << 1) << 2 * (levels - l), rid) for l, cx, cy, rid in leaves)
    runs = []
    for k, rid in keyed:
        if not runs or runs[-1][1] != rid:
            runs.append((k, rid))
    return levels, runs


def write_cpp(path, levels, runs, regions):
    n_names = max(regions) + 1
    esc = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
    out = ["// Generated by scripts/regions/build_regions.py from data/regions/. Do not edit.",
           "#include <cstdint>", "",
           "extern const uint16_t region_levels = %d;" % levels,
           "extern const uint32_t region_count = %d;" % len(runs), "",
           "extern const uint32_t region_start[%d] = {" % len(runs)]
    out += ["\t" + ",".join("0x%08x" % k for k, _ in runs[i:i + 8]) + "," for i in range(0, len(runs), 8)]
    out += ["};", "", "extern const uint16_t region_id[%d] = {" % len(runs)]
    out += ["\t" + ",".join(str(r) for _, r in runs[i:i + 16]) + "," for i in range(0, len(runs), 16)]
    out += ["};", "", "extern const uint16_t region_name_count = %d;" % n_names,
            "extern const char *const region_name[%d] = {" % n_names]
    out += ['\t"%s",' % (esc(regions[i].name) if i in regions else "") for i in range(n_names)]
    out += ["};", ""]
    open(path, "w", encoding="utf-8").write("\n".join(out))


def write_js(path, regions):
    names = {r.id: r.name for r in regions.values() if r.name}
    open(path, "w", encoding="utf-8").write(
        "// Generated by scripts/regions/build_regions.py from data/regions/. Do not edit.\n"
        "export default " + json.dumps(names, ensure_ascii=False, separators=(",", ":")) + ";\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default="data/regions")
    ap.add_argument("--cpp", default="Source/Tracking/RegionTree.cpp")
    ap.add_argument("--js", default="frontend/src/core/regionNames.js")
    ap.add_argument("--csv", help="also write id,name,featurecla, for a database that stores region ids")
    a = ap.parse_args()

    t0 = time.time()
    regions = load(a.src)
    leaves = build(regions)
    levels, runs = runs_of(leaves)
    write_cpp(a.cpp, levels, runs, regions)
    write_js(a.js, regions)
    if a.csv:
        with open(a.csv, "w", encoding="utf-8") as f:
            f.write("id,name,featurecla\n")
            for r in sorted(regions.values()):
                f.write('%d,"%s",%s\n' % (r.id, r.name.replace('"', '""'), r.featurecla))
    print("%d regions, %d leaves -> %d runs, %d levels, %.1f s -> %s, %s"
          % (len(regions), len(leaves), len(runs), levels, time.time() - t0, a.cpp, a.js))


if __name__ == "__main__":
    main()
