if(MSVC AND NOT MSVC_VCPKG)
    if(EXISTS "${POTHOSSDR_BINARY_DIR}/libssl-3-x64.dll")
        set(OPENSSL_DLL "${POTHOSSDR_BINARY_DIR}/libssl-3-x64.dll")
    elseif(EXISTS "${POTHOSSDR_BINARY_DIR}/libssl-3.dll")
        set(OPENSSL_DLL "${POTHOSSDR_BINARY_DIR}/libssl-3.dll")
    endif()
    message(STATUS "OpenSSL DLL: ${OPENSSL_DLL}")

    if(EXISTS "${POTHOSSDR_BINARY_DIR}/libcrypto-3-x64.dll")
        set(CRYPTO_DLL "${POTHOSSDR_BINARY_DIR}/libcrypto-3-x64.dll")
    elseif(EXISTS "${POTHOSSDR_BINARY_DIR}/libcrypto-3.dll")
        set(CRYPTO_DLL "${POTHOSSDR_BINARY_DIR}/libcrypto-3.dll")
    endif()
    message(STATUS "Crypto DLL: ${CRYPTO_DLL}")
endif()

# Find ssl
if(OPENSSL)
    if(MSVC AND NOT MSVC_VCPKG)

        find_path(OPENSSL_INCLUDE_DIR openssl/ssl.h HINTS ${POTHOSSDR_INCLUDE_DIR})
        find_library(OPENSSL_LIBRARY libssl.lib HINTS ${POTHOSSDR_LIBRARY_DIR})

        if(OPENSSL_INCLUDE_DIR AND OPENSSL_LIBRARY AND OPENSSL_DLL AND CRYPTO_DLL)
            Message(STATUS "OPENSSL: found (PothosSDR) - " ${OPENSSL_INCLUDE_DIR}, ${OPENSSL_LIBRARY}, ${OPENSSL_DLL}, ${CRYPTO_DLL})
            set(COPY_OPENSSL_DLL TRUE)
            add_definitions(-DHASOPENSSL)

            set(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
            set(OPENSSL_LIBRARIES ${OPENSSL_LIBRARY})
        else()
            Message(STATUS "OPENSSL: NOT found (PothosSDR) - " ${OPENSSL_INCLUDE_DIR}, ${OPENSSL_LIBRARY}, ${OPENSSL_DLL}, ${CRYPTO_DLL})
        endif()
    else()

        pkg_check_modules(PKG_SSL libssl)
        find_path(SSL_INCLUDE_DIR openssl/ssl.h HINTS ${PKG_SSL_INCLUDE_DIRS})
        if(STATIC)
            find_library(SSL_LIBRARY NAMES libssl.a HINTS ${PKG_SSL_LIBRARY_DIRS})
            find_library(CRYPTO_LIBRARY NAMES libcrypto.a HINTS ${PKG_SSL_LIBRARY_DIRS})
        else()
            find_library(SSL_LIBRARY NAMES libssl.so libssl.dylib HINTS ${PKG_SSL_LIBRARY_DIRS})
            find_library(CRYPTO_LIBRARY NAMES libcrypto.so libcrypto.dylib HINTS ${PKG_SSL_LIBRARY_DIRS})
        endif()

        if(SSL_INCLUDE_DIR AND SSL_LIBRARY AND CRYPTO_LIBRARY)
            message(STATUS "OPENSSL: found - ${SSL_INCLUDE_DIR}, ${SSL_LIBRARY}, ${CRYPTO_LIBRARY}")
            add_definitions(-DHASOPENSSL)
            set(OPENSSL_INCLUDE_DIRS ${SSL_INCLUDE_DIR})
            set(OPENSSL_LIBRARIES ${SSL_LIBRARY} ${CRYPTO_LIBRARY})
        else()
            message(STATUS "OPENSSL: not found - ${SSL_INCLUDE_DIR}, ${SSL_LIBRARY}, ${CRYPTO_LIBRARY}")
        endif()

    endif()
endif()
