#!/usr/bin/env python3
"""Generate aiscat/types.py — TypedDicts per AIS message type.

Reads ~/website/static/msgs.json (the corpus of example NMEA sentences),
feeds them through the installed aiscat decoder, and records observed
Python types per key per AIS message type. Emits aiscat/types.py with one
TypedDict per type, plus an AISMessage union alias.

Run after upstream KeyDefs.h changes or when expanding the corpus.
"""

import json
import pathlib
import sys
from collections import defaultdict

try:
    import aiscat
except ImportError:
    sys.exit("aiscat not installed — run `pip install -e .` from python/ first")

CORPUS = pathlib.Path.home() / "website/static/msgs.json"
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/aiscat/types.py"


def py_type_name(value):
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, str):
        return "str"
    if isinstance(value, list):
        if not value:
            return "list[str]"
        inner = py_type_name(value[0])
        return f"list[{inner}]"
    if value is None:
        return "None"
    return "Any"


def main():
    if not CORPUS.exists():
        sys.exit(f"corpus missing: {CORPUS}")
    data = json.loads(CORPUS.read_text())

    # per_type[ais_type][key] = set of seen Python type names
    per_type = defaultdict(lambda: defaultdict(set))

    for entry in data:
        ais_type = entry.get("type")
        if ais_type is None:
            continue
        for grp in entry.get("nmea", []):
            dec = aiscat.Decoder()
            for line in grp:
                dec.feed(line.encode() + b"\r\n")
            m = dec.next()
            while m is not None:
                t = m.get("type")
                if t is not None:
                    for k, v in m.items():
                        per_type[t][k].add(py_type_name(v))
                m = dec.next()

    if not per_type:
        sys.exit("no messages decoded — check corpus and decoder")

    # Render
    PRIORITY = ["type", "mmsi", "channel", "rxuxtime"]
    lines = [
        "# Auto-generated by scripts/gen_types.py from msgs.json corpus — DO NOT EDIT.",
        "# Regenerate after upstream KeyDefs.h changes or corpus expansion.",
        "",
        "from __future__ import annotations",
        "",
        "from typing import TypedDict, Union",
        "",
    ]

    class_names = []
    for ais_type in sorted(per_type.keys()):
        cls = f"Type{ais_type}"
        class_names.append(cls)
        lines.append(f"class {cls}(TypedDict, total=False):")
        lines.append(f'    """AIS message type {ais_type}."""')
        keys = list(per_type[ais_type].keys())
        ordered = [k for k in PRIORITY if k in keys] + sorted(
            k for k in keys if k not in PRIORITY
        )
        for k in ordered:
            types = sorted(per_type[ais_type][k])
            t = types[0] if len(types) == 1 else " | ".join(types)
            lines.append(f"    {k}: {t}")
        lines.append("")

    lines.append(f"AISMessage = Union[{', '.join(class_names)}]")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    n_keys = sum(len(v) for v in per_type.values())
    print(f"wrote {OUT}")
    print(f"  {len(per_type)} message types, {n_keys} key entries total")


if __name__ == "__main__":
    main()
