# Auto-generated by scripts/gen_types.py from msgs.json corpus — DO NOT EDIT.
# Regenerate after upstream KeyDefs.h changes or corpus expansion.

from __future__ import annotations

from typing import TypedDict, Union

class Type1(TypedDict, total=False):
    """AIS message type 1."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    course: float
    heading: int
    lat: float
    lon: float
    maneuver: int
    power: bool
    radio: int
    raim: bool
    received_stations: int
    repeat: int
    second: int
    slot_number: int
    slot_timeout: int
    speed: float
    status: int
    status_text: str
    sync_state: int
    turn: int
    turn_unscaled: int
    utc_hour: int
    utc_minute: int

class Type2(TypedDict, total=False):
    """AIS message type 2."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    course: float
    heading: int
    lat: float
    lon: float
    maneuver: int
    power: bool
    radio: int
    raim: bool
    received_stations: int
    repeat: int
    second: int
    slot_number: int
    slot_offset: int
    slot_timeout: int
    speed: float
    status: int
    status_text: str
    sync_state: int
    turn: int
    turn_unscaled: int

class Type3(TypedDict, total=False):
    """AIS message type 3."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    course: float
    heading: int
    lat: float
    lon: float
    maneuver: int
    power: bool
    radio: int
    raim: bool
    repeat: int
    second: int
    slot_offset: int
    slot_timeout: int
    speed: float
    status: int
    status_text: str
    sync_state: int
    turn: int
    turn_unscaled: int

class Type4(TypedDict, total=False):
    """AIS message type 4."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    day: int
    epfd: int
    epfd_text: str
    hour: int
    lat: float
    lon: float
    minute: int
    month: int
    radio: int
    raim: bool
    repeat: int
    second: int
    slot_number: int
    slot_timeout: int
    sync_state: int
    timestamp: str
    transmission_control: bool
    utc_hour: int
    utc_minute: int
    year: int

class Type5(TypedDict, total=False):
    """AIS message type 5."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    ais_version: int
    callsign: str
    day: int
    destination: str
    draught: float
    dte: bool
    epfd: int
    epfd_text: str
    eta: str
    hour: int
    imo: int
    minute: int
    month: int
    repeat: int
    shipname: str
    shiptype: int
    shiptype_text: str
    to_bow: int
    to_port: int
    to_starboard: int
    to_stern: int

class Type6(TypedDict, total=False):
    """AIS message type 6."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    ack_required: bool
    ana_ext1: float
    ana_ext2: float
    ana_int: float
    asm_battery_status: bool
    asm_current_data: float
    asm_light_status: bool
    asm_off_position_status: bool
    asm_power_supply_type: bool
    asm_sub_app_id: int
    asm_voltage_data: float
    crew_count: int
    dac: int
    data: str
    dest_mmsi: int
    fid: int
    health: int
    lat: float
    lon: float
    message_id: int
    off_position: bool
    passenger_count: int
    persons: int
    racon: int
    repeat: int
    requested_dac: int
    requested_fid: int
    retransmit: bool
    seqno: int
    shipboard_personnel_count: int
    stat_ext: int
    station_name: str
    text: str
    text_sequence: int
    utc_day: int
    utc_hour: int
    utc_minute: int

class Type7(TypedDict, total=False):
    """AIS message type 7."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    mmsi1: int
    mmsiseq1: int
    repeat: int

class Type8(TypedDict, total=False):
    """AIS message type 8."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    ack_required: bool
    airtemp: float
    alt: int
    asm_version: int
    beam: float
    bridge_clearance: int
    cdir: int
    cdir2: int
    cdir3: int
    clearance_accuracy: int
    course_q: bool
    cspeed: float
    dac: int
    data: str
    day: int
    dewpoint: float
    draught: float
    fairway_hectometre: int
    fairway_section: int
    fid: int
    forecast_duration: int
    forecast_wgust: int
    forecast_wspeed: int
    hazard: int
    heading_q: bool
    hour: int
    humidity: int
    lat: float
    length: float
    linkage_id: int
    loaded: int
    lon: float
    measurement_age: int
    message_id: int
    minute: int
    month: int
    name: str
    object_code: str
    preciptype: int
    precision: int
    pressure: int
    pressuretend: int
    pressuretend_wmo: int
    reading_type: int
    reference_datum: int
    repeat: int
    report_type: int
    route_type: int
    salinity: float
    seastate: int
    sender_classification: int
    sensor_description: int
    sensor_report_type: int
    shiptype: int
    site_id: int
    speed_q: bool
    station_id: str
    station_name: str
    swelldir: int
    swellheight: float
    text: str
    text_sequence: int
    un_country: str
    vin: str
    visgreater: bool
    visibility: float
    vts_target_cog: int
    vts_target_id: int
    vts_target_id_type: int
    vts_target_lat: float
    vts_target_lon: float
    vts_target_sog: int
    vts_target_timestamp: int
    water_flow: int
    water_level_type: int
    waterlevel: float
    watertemp: float
    wavedir: int
    waveheight: float
    waypoint_count: int
    waypoints: str
    wdir: int
    weather_report_type: int
    wgust: int
    wgustdir: int
    wspeed: int

class Type9(TypedDict, total=False):
    """AIS message type 9."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    alt: int
    alt_sensor: bool
    assigned: bool
    course: float
    dte: bool
    lat: float
    lon: float
    radio: int
    raim: bool
    repeat: int
    second: int
    speed: int

class Type10(TypedDict, total=False):
    """AIS message type 10."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    dest_mmsi: int
    repeat: int

class Type11(TypedDict, total=False):
    """AIS message type 11."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    day: int
    epfd: int
    epfd_text: str
    hour: int
    lat: float
    lon: float
    minute: int
    month: int
    radio: int
    raim: bool
    repeat: int
    second: int
    timestamp: str
    transmission_control: bool
    year: int

class Type12(TypedDict, total=False):
    """AIS message type 12."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    dest_mmsi: int
    repeat: int
    retransmit: bool
    seqno: int
    text: str

class Type13(TypedDict, total=False):
    """AIS message type 13."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    mmsi1: int
    mmsiseq1: int
    repeat: int

class Type14(TypedDict, total=False):
    """AIS message type 14."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    repeat: int
    text: str

class Type15(TypedDict, total=False):
    """AIS message type 15."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    mmsi1: int
    mmsi2: int
    offset1_1: int
    offset1_2: int
    offset2_1: int
    repeat: int
    type1_1: int
    type1_2: int
    type2_1: int

class Type16(TypedDict, total=False):
    """AIS message type 16."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    increment1: int
    increment2: int
    mmsi1: int
    mmsi2: int
    offset1: int
    offset2: int
    repeat: int

class Type17(TypedDict, total=False):
    """AIS message type 17."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    data: str
    lat: float
    lon: float
    repeat: int

class Type18(TypedDict, total=False):
    """AIS message type 18."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    assigned: bool
    band: bool
    course: float
    cs: bool
    display: bool
    dsc: bool
    heading: int
    lat: float
    lon: float
    msg22: bool
    power: bool
    radio: int
    raim: bool
    repeat: int
    reserved: int
    second: int
    speed: float

class Type19(TypedDict, total=False):
    """AIS message type 19."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    assigned: bool
    course: float
    dte: bool
    epfd: int
    epfd_text: str
    heading: int
    lat: float
    lon: float
    raim: bool
    repeat: int
    second: int
    shipname: str
    shiptype: int
    shiptype_text: str
    speed: float
    to_bow: int
    to_port: int
    to_starboard: int
    to_stern: int

class Type20(TypedDict, total=False):
    """AIS message type 20."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    increment1: int
    increment2: int
    number1: int
    number2: int
    offset1: int
    offset2: int
    repeat: int
    timeout1: int
    timeout2: int

class Type21(TypedDict, total=False):
    """AIS message type 21."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: bool
    aid_type: int
    aid_type_text: str
    assigned: bool
    aton_status: int
    epfd: int
    epfd_text: str
    lat: float
    lon: float
    name: str
    off_position: bool
    raim: bool
    repeat: int
    second: int
    to_bow: int
    to_port: int
    to_starboard: int
    to_stern: int
    virtual_aid: bool

class Type22(TypedDict, total=False):
    """AIS message type 22."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    addressed: bool
    band_a: bool
    band_b: bool
    channel_a: int
    channel_b: int
    ne_lat: float
    ne_lon: float
    power: bool
    repeat: int
    sw_lat: float
    sw_lon: float
    txrx: int
    zonesize: int

class Type23(TypedDict, total=False):
    """AIS message type 23."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    interval: int
    ne_lat: float
    ne_lon: float
    quiet: int
    repeat: int
    shiptype: int
    shiptype_text: str
    station_type: int
    sw_lat: float
    sw_lon: float
    txrx: int

class Type24(TypedDict, total=False):
    """AIS message type 24."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    callsign: str
    epfd: int
    epfd_text: str
    model: int
    partno: int
    repeat: int
    serial: int
    shipname: str
    shiptype: int
    shiptype_text: str
    to_bow: int
    to_port: int
    to_starboard: int
    to_stern: int
    vdes_capabilities: int
    vendorid: str

class Type25(TypedDict, total=False):
    """AIS message type 25."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    addressed: bool
    ai_available: bool
    repeat: int

class Type26(TypedDict, total=False):
    """AIS message type 26."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    addressed: bool
    ai_available: bool
    ana_ext1: float
    ana_ext2: float
    ana_int: float
    dac: int
    data: str
    fid: int
    health: int
    off_position: bool
    racon: int
    radio: int
    repeat: int
    stat_ext: int

class Type27(TypedDict, total=False):
    """AIS message type 27."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    accuracy: int
    course: int
    gnss: int
    lat: float
    lon: float
    raim: int
    repeat: int
    speed: int
    status: int
    status_text: str

class Type28(TypedDict, total=False):
    """AIS message type 28."""
    type: int
    mmsi: int
    channel: str
    rxuxtime: float
    additional_flag: bool
    aid_type: int
    aid_type_text: str
    aton_station_type: int
    aton_status: int
    auth_flag: bool
    charted_status: bool
    dim_type: int
    iala_mrn: int
    lat: float
    lon: float
    on_station_status: int
    repeat: int
    restricted_use: int
    second: int
    to_bow: int
    to_stern: int
    virtual_aid: bool

AISMessage = Union[Type1, Type2, Type3, Type4, Type5, Type6, Type7, Type8, Type9, Type10, Type11, Type12, Type13, Type14, Type15, Type16, Type17, Type18, Type19, Type20, Type21, Type22, Type23, Type24, Type25, Type26, Type27, Type28]
